/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.lette1394.numberbaseball;

import java.util.Random;
import java.util.Scanner;

public class Main {
  public static void main(String[] args) {

    int com[] = new int[3]; // 컴퓨터 숫자

    Random r = new Random();
    // 랜덤 숫자 생성
    while (com[0] == 0) {
      com[0] = r.nextInt(10);
    }
    while (com[0] == com[1] || com[1] == 0) {
      com[1] = r.nextInt(10);
    }
    while (com[1] == com[2] || com[2] == 0) {
      com[2] = r.nextInt(10);
    }

    new Game().run(com);
  }
}
